name: Publish Checkout.podspec

on: workflow_dispatch

jobs:
  publish:
    environment: CocoaPodsRelease
    runs-on: macos-12-xl
    steps:
      - uses: actions/checkout@v4
      
      - name: Check current branch
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" != "main" && "${GITHUB_REF#refs/heads/}" != release/* ]]; then
            echo "This workflow is expected to run on the main or release branch only."
            exit 1
          fi

      - name: Publish Checkout.podspec
        run: |
          gem install cocoapods
          pod trunk push Checkout.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
